"""
! what?
signlas are an operating system feature that provide a means of notifying a program event,
and having it handled asynchronously.

They can be generated by the system itself,
or sent from one process to another.

Since signals interrupt the regular flow of the program,
it is possbile that some operations (especially I/O) may produce
errors if a signal is received while they are ongoing


! why?
signals are identified by integers and are defined in the operating system C headers.
Python exposes the signals appropriate for the platform as symbols in the `signal` module.


! how?
the examples in this section use `SIGINT` and `SIGUSR1`,
both of which are typically defined for all unix and unix=like system

signal
|-- receive signals
|-- retrieve registered handlers
|-- send signals
|-- alarms
|-- ingore signals
|-- signals and threads

"""